# Example 1: (Read file)
# var_file=open('Read_file.txt','r')
# print(var_file.read())
# print('************')
# var_file=open('Read_file.txt','r')
# print(var_file.readline())
# print('************')
# var_file=open('Read_file.txt','r')
# print(var_file.readlines())
# print('************')
# var_file=open('Read_file.txt','r')
# for line in var_file:
#     print(line)
# var_file.close()

# Example 2: (Write file)
var_file=open('Write_file.txt','w')
var_file.write('ABBC\n')
var_file=open('Write_file.txt','r')
print(var_file.read())
print('************')
var_file.close()
# ---------------------------------
var_file=open('Write_file.txt','w')
var_file.write('ABBC\n')
var_file=open('Write_file.txt','r')
print(var_file.read())
print('************')
var_file.close()
# ---------------------------------
var_file=open('Write_file.txt','a')
var_file.write('This is a new line')
var_file=open('Write_file.txt','r')
print(var_file.read())
print('************')